//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCRAT.Web {
    
    
    public partial class about_tool {
        
        /// <summary>
        /// PageOptions1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PageOptions PageOptions1;
        
        /// <summary>
        /// lnlNewCal control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink lnlNewCal;
        
        /// <summary>
        /// AboutExplanation1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.AboutExplanation AboutExplanation1;
        
        /// <summary>
        /// AboutExplanation2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.AboutExplanation AboutExplanation2;
        
        /// <summary>
        /// ae1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.AboutExplanation ae1;
        
        /// <summary>
        /// AboutExplanation4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.AboutExplanation AboutExplanation4;
        
        /// <summary>
        /// AboutExplanation7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.AboutExplanation AboutExplanation7;
        
        /// <summary>
        /// AboutExplanation8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.AboutExplanation AboutExplanation8;
        
        /// <summary>
        /// AboutExplanation9 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.AboutExplanation AboutExplanation9;
        
        /// <summary>
        /// AboutExplanation10 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.AboutExplanation AboutExplanation10;
        
        /// <summary>
        /// AboutExplanation11 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.AboutExplanation AboutExplanation11;
        
        /// <summary>
        /// AboutExplanation12 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.AboutExplanation AboutExplanation12;
        
        /// <summary>
        /// AboutExplanation13 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.AboutExplanation AboutExplanation13;
        
        /// <summary>
        /// AboutExplanation14 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.AboutExplanation AboutExplanation14;
    }
}
