//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


public partial class resimpact {
    protected System.Web.UI.WebControls.Label lblBlack;
    protected System.Web.UI.WebControls.Label lblHispanic;
    protected System.Web.UI.WebControls.Label lblAsianOrPI;
    protected System.Web.UI.WebControls.Label lblAmIndianOrAN;
    protected System.Web.UI.WebControls.Label lblUnknown;
}
