//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCRAT.Web.UserControls {
    
    
    public partial class QuestionAsker2 {
        
        /// <summary>
        /// pQuestionsRequired control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pQuestionsRequired;
        
        /// <summary>
        /// qgmManager control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionGroupManager qgmManager;
        
        /// <summary>
        /// qgHispanic control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionGroup qgHispanic;
        
        /// <summary>
        /// qcHispanic control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionControl qcHispanic;
        
        /// <summary>
        /// ddlHispanic control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlHispanic;
        
        /// <summary>
        /// qeHispanic control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionExplanation qeHispanic;
        
        /// <summary>
        /// qgRace control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionGroup qgRace;
        
        /// <summary>
        /// qsRace control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionSeparator qsRace;
        
        /// <summary>
        /// qcRace control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionControl qcRace;
        
        /// <summary>
        /// ddlRace control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlRace;
        
        /// <summary>
        /// qeRace control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionExplanation qeRace;
        
        /// <summary>
        /// qgCurrentAge control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionGroup qgCurrentAge;
        
        /// <summary>
        /// qsCurrentAge control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionSeparator qsCurrentAge;
        
        /// <summary>
        /// qcCurrentAge control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionControl qcCurrentAge;
        
        /// <summary>
        /// ddlCurrentAge control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlCurrentAge;
        
        /// <summary>
        /// qeCurrentAge control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionExplanation qeCurrentAge;
        
        /// <summary>
        /// qgGender control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionGroup qgGender;
        
        /// <summary>
        /// qsGender control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionSeparator qsGender;
        
        /// <summary>
        /// qcGender control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionControl qcGender;
        
        /// <summary>
        /// ddlGender control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlGender;
        
        /// <summary>
        /// qeGender control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionExplanation qeGender;
        
        /// <summary>
        /// qgNumServingsVeg control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionGroup qgNumServingsVeg;
        
        /// <summary>
        /// QuestionSeparator18 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionSeparator QuestionSeparator18;
        
        /// <summary>
        /// qcHeight control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionControl qcHeight;
        
        /// <summary>
        /// ddlHeightFeet control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlHeightFeet;
        
        /// <summary>
        /// lblHeightFeet control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblHeightFeet;
        
        /// <summary>
        /// ddlHeightInches control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlHeightInches;
        
        /// <summary>
        /// lblHeightInches control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblHeightInches;
        
        /// <summary>
        /// qeHeight control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionExplanation qeHeight;
        
        /// <summary>
        /// qsWeight control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionSeparator qsWeight;
        
        /// <summary>
        /// qcWeight control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionControl qcWeight;
        
        /// <summary>
        /// txtWeight control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtWeight;
        
        /// <summary>
        /// lblWeight control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblWeight;
        
        /// <summary>
        /// qeWeight control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionExplanation qeWeight;
        
        /// <summary>
        /// qsHeight control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionSeparator qsHeight;
        
        /// <summary>
        /// qshNumServingsVeg control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionSectionHeader qshNumServingsVeg;
        
        /// <summary>
        /// qcNumServingsVeg control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionControl qcNumServingsVeg;
        
        /// <summary>
        /// ddlNumServingsVeg control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlNumServingsVeg;
        
        /// <summary>
        /// qeNumServingsVeg control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionExplanation qeNumServingsVeg;
        
        /// <summary>
        /// qgAmountVeg control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionGroup qgAmountVeg;
        
        /// <summary>
        /// qsAmountVeg control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionSeparator qsAmountVeg;
        
        /// <summary>
        /// qcAmountVeg control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionControl qcAmountVeg;
        
        /// <summary>
        /// ddlAmountVeg control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlAmountVeg;
        
        /// <summary>
        /// qeAmountVeg control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionExplanation qeAmountVeg;
        
        /// <summary>
        /// qgColonoscopy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionGroup qgColonoscopy;
        
        /// <summary>
        /// qsColonoscopy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionSeparator qsColonoscopy;
        
        /// <summary>
        /// qcColonoscopy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionControl qcColonoscopy;
        
        /// <summary>
        /// ddlColonoscopy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlColonoscopy;
        
        /// <summary>
        /// qeColonoscopy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionExplanation qeColonoscopy;
        
        /// <summary>
        /// qgHadPolyp control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionGroup qgHadPolyp;
        
        /// <summary>
        /// qsHadPolyp control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionSeparator qsHadPolyp;
        
        /// <summary>
        /// qcHadPolyp control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionControl qcHadPolyp;
        
        /// <summary>
        /// ddlHadPolyp control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlHadPolyp;
        
        /// <summary>
        /// qeHadPolyp control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionExplanation qeHadPolyp;
        
        /// <summary>
        /// qgAsprin control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionGroup qgAsprin;
        
        /// <summary>
        /// QuestionSeparator19 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionSeparator QuestionSeparator19;
        
        /// <summary>
        /// QuestionSeparator1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionSectionHeader QuestionSeparator1;
        
        /// <summary>
        /// qcAsprin control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionControl qcAsprin;
        
        /// <summary>
        /// ddlAsprin control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlAsprin;
        
        /// <summary>
        /// qeAsprin control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionExplanation qeAsprin;
        
        /// <summary>
        /// qgIbuprofen control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionGroup qgIbuprofen;
        
        /// <summary>
        /// QuestionSeparator2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionSeparator QuestionSeparator2;
        
        /// <summary>
        /// qcIbuprofen control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionControl qcIbuprofen;
        
        /// <summary>
        /// ddlIbuprofen control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlIbuprofen;
        
        /// <summary>
        /// qeIbuprofen control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionExplanation qeIbuprofen;
        
        /// <summary>
        /// qgModerateActivities control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionGroup qgModerateActivities;
        
        /// <summary>
        /// QuestionSeparator20 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionSeparator QuestionSeparator20;
        
        /// <summary>
        /// QuestionSeparator3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionSectionHeader QuestionSeparator3;
        
        /// <summary>
        /// qcModerateActivities control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionControl qcModerateActivities;
        
        /// <summary>
        /// ddlModerateActivities control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlModerateActivities;
        
        /// <summary>
        /// qeModerateActivities control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionExplanation qeModerateActivities;
        
        /// <summary>
        /// qgModerateHours control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionGroup qgModerateHours;
        
        /// <summary>
        /// QuestionSeparator4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionSeparator QuestionSeparator4;
        
        /// <summary>
        /// qcModerateHours control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionControl qcModerateHours;
        
        /// <summary>
        /// ddlModerateHours control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlModerateHours;
        
        /// <summary>
        /// qeModerateHours control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionExplanation qeModerateHours;
        
        /// <summary>
        /// qgVigorousActivities control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionGroup qgVigorousActivities;
        
        /// <summary>
        /// QuestionSeparator5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionSeparator QuestionSeparator5;
        
        /// <summary>
        /// qcVigorousActivities control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionControl qcVigorousActivities;
        
        /// <summary>
        /// ddlVigorousActivities control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlVigorousActivities;
        
        /// <summary>
        /// qeVigorousActivities control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionExplanation qeVigorousActivities;
        
        /// <summary>
        /// qgVigorousHours control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionGroup qgVigorousHours;
        
        /// <summary>
        /// QuestionSeparator6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionSeparator QuestionSeparator6;
        
        /// <summary>
        /// qcVigorousHours control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionControl qcVigorousHours;
        
        /// <summary>
        /// ddlVigorousHours control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlVigorousHours;
        
        /// <summary>
        /// qeVigorousHours control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionExplanation qeVigorousHours;
        
        /// <summary>
        /// qg100MoreCigs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionGroup qg100MoreCigs;
        
        /// <summary>
        /// QuestionSeparator7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionSeparator QuestionSeparator7;
        
        /// <summary>
        /// qc100MoreCigs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionControl qc100MoreCigs;
        
        /// <summary>
        /// ddl100MoreCigs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddl100MoreCigs;
        
        /// <summary>
        /// qe100MoreCigs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionExplanation qe100MoreCigs;
        
        /// <summary>
        /// qgStartSmoke control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionGroup qgStartSmoke;
        
        /// <summary>
        /// QuestionSeparator8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionSeparator QuestionSeparator8;
        
        /// <summary>
        /// qcStartSmoke control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionControl qcStartSmoke;
        
        /// <summary>
        /// ddlStartSmoke control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlStartSmoke;
        
        /// <summary>
        /// qeStartSmoke control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionExplanation qeStartSmoke;
        
        /// <summary>
        /// qgStillSmoke control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionGroup qgStillSmoke;
        
        /// <summary>
        /// QuestionSeparator9 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionSeparator QuestionSeparator9;
        
        /// <summary>
        /// qcStillSmoke control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionControl qcStillSmoke;
        
        /// <summary>
        /// ddlStillSmoke control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlStillSmoke;
        
        /// <summary>
        /// qeStillSmoke control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionExplanation qeStillSmoke;
        
        /// <summary>
        /// qgSmokeQuit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionGroup qgSmokeQuit;
        
        /// <summary>
        /// QuestionSeparator10 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionSeparator QuestionSeparator10;
        
        /// <summary>
        /// qcSmokeQuit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionControl qcSmokeQuit;
        
        /// <summary>
        /// ddlSmokeQuit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlSmokeQuit;
        
        /// <summary>
        /// qeSmokeQuit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionExplanation qeSmokeQuit;
        
        /// <summary>
        /// qgCigNumPerDay control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionGroup qgCigNumPerDay;
        
        /// <summary>
        /// QuestionSeparator11 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionSeparator QuestionSeparator11;
        
        /// <summary>
        /// qcCigNumPerDay control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionControl qcCigNumPerDay;
        
        /// <summary>
        /// ddlCigNumPerDay control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlCigNumPerDay;
        
        /// <summary>
        /// qeCigNumPerDay control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionExplanation qeCigNumPerDay;
        
        /// <summary>
        /// qgStillHavePeriods control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionGroup qgStillHavePeriods;
        
        /// <summary>
        /// QuestionSeparator12 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionSeparator QuestionSeparator12;
        
        /// <summary>
        /// qcStillHavePeriods control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionControl qcStillHavePeriods;
        
        /// <summary>
        /// ddlStillHavePeriods control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlStillHavePeriods;
        
        /// <summary>
        /// qeStillHavePeriods control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionExplanation qeStillHavePeriods;
        
        /// <summary>
        /// qgLastCycle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionGroup qgLastCycle;
        
        /// <summary>
        /// QuestionSeparator13 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionSeparator QuestionSeparator13;
        
        /// <summary>
        /// qcLastCycle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionControl qcLastCycle;
        
        /// <summary>
        /// ddlLastCycle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlLastCycle;
        
        /// <summary>
        /// qeLastCycle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionExplanation qeLastCycle;
        
        /// <summary>
        /// qgUsedEstrogen control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionGroup qgUsedEstrogen;
        
        /// <summary>
        /// QuestionSeparator14 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionSeparator QuestionSeparator14;
        
        /// <summary>
        /// qcUsedEstrogen control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionControl qcUsedEstrogen;
        
        /// <summary>
        /// ddlUsedEstrogen control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlUsedEstrogen;
        
        /// <summary>
        /// qeUsedEstrogen control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionExplanation qeUsedEstrogen;
        
        /// <summary>
        /// qgHasRelativeHadCC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionGroup qgHasRelativeHadCC;
        
        /// <summary>
        /// QuestionSeparator21 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionSeparator QuestionSeparator21;
        
        /// <summary>
        /// QuestionSeparator15 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionSectionHeader QuestionSeparator15;
        
        /// <summary>
        /// qcHasRelativeHadCC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionControl qcHasRelativeHadCC;
        
        /// <summary>
        /// ddlHasRelativeHadCC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlHasRelativeHadCC;
        
        /// <summary>
        /// qeHasRelativeHadCC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionExplanation qeHasRelativeHadCC;
        
        /// <summary>
        /// qgNumRelativesHavingCC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionGroup qgNumRelativesHavingCC;
        
        /// <summary>
        /// QuestionSeparator16 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionSeparator QuestionSeparator16;
        
        /// <summary>
        /// qcNumRelativesHavingCC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionControl qcNumRelativesHavingCC;
        
        /// <summary>
        /// ddlNumRelativesHavingCC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlNumRelativesHavingCC;
        
        /// <summary>
        /// qeNumRelativesHavingCC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionExplanation qeNumRelativesHavingCC;
        
        /// <summary>
        /// QuestionSeparator17 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CCRAT.QuestionSeparator QuestionSeparator17;
        
        /// <summary>
        /// phCalculateButtons control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder phCalculateButtons;
        
        /// <summary>
        /// btnCalculateDisabled control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image btnCalculateDisabled;
        
        /// <summary>
        /// btnCalculate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ImageButton btnCalculate;
        
        /// <summary>
        /// lnkNewCalculation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink lnkNewCalculation;
        
        /// <summary>
        /// imgNewCalculation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image imgNewCalculation;
    }
}
